// 30 Zufallsereignis-Texte (Konzept Abschnitt 10): 15 Golden Meme + 15 Bubble Pop
export const EVENTS_CONTENT = {
  golden_1: { de: { title: "🟢 Tech-Milliardär antwortet 'interessant' auf euren Post", desc: "10x TPS für 30 Sekunden – per Video sichern!" }, en: { title: "🟢 Tech Billionaire Replies 'Interesting' to Your Post", desc: "10x TPS for 30 seconds – claim by video!" } },
  golden_2: { de: { title: "🟢 Analyst nennt euch 'das nächste große Ding'. Schon wieder.", desc: "10x TPS für 30 Sekunden – per Video sichern!" }, en: { title: "🟢 Analyst Calls You 'The Next Big Thing'. Again.", desc: "10x TPS for 30 seconds – claim by video!" } },
  golden_3: { de: { title: "🟢 Accelerator gratuliert per Serienbrief", desc: "10x TPS für 30 Sekunden – per Video sichern!" }, en: { title: "🟢 Accelerator Sends Congratulations via Mail Merge", desc: "10x TPS for 30 seconds – claim by video!" } },
  golden_4: { de: { title: "🟢 '30 unter 30'-Nominierung, Gebühr bereits abgebucht", desc: "10x TPS für 30 Sekunden – per Video sichern!" }, en: { title: "🟢 '30 Under 30' Nomination, Fee Already Charged", desc: "10x TPS for 30 seconds – claim by video!" } },
  golden_5: { de: { title: "🟢 Wettbewerber kopiert euren Bug und nennt ihn Feature", desc: "10x TPS für 30 Sekunden – per Video sichern!" }, en: { title: "🟢 Competitor Copies Your Bug, Ships It as a Feature", desc: "10x TPS for 30 seconds – claim by video!" } },
  golden_6: { de: { title: "🟢 Investor teilt euren Launch, ohne ihn gelesen zu haben", desc: "10x TPS für 30 Sekunden – per Video sichern!" }, en: { title: "🟢 Investor Shares Your Launch Without Reading It", desc: "10x TPS for 30 seconds – claim by video!" } },
  golden_7: { de: { title: "🟢 Fachpresse übernimmt eure Pressemitteilung wörtlich", desc: "10x TPS für 30 Sekunden – per Video sichern!" }, en: { title: "🟢 Trade Press Reprints Your Press Release Verbatim", desc: "10x TPS for 30 seconds – claim by video!" } },
  golden_8: { de: { title: "🟢 Konkurrent ist insolvent, ihr erbt deren Beschwerden", desc: "10x TPS für 30 Sekunden – per Video sichern!" }, en: { title: "🟢 Competitor Folds, You Inherit Their Complaints", desc: "10x TPS for 30 seconds – claim by video!" } },
  golden_9: { de: { title: "🟢 Demo-Clip geht viral, aus den falschen Gründen", desc: "10x TPS für 30 Sekunden – per Video sichern!" }, en: { title: "🟢 Demo Clip Goes Viral for the Wrong Reasons", desc: "10x TPS for 30 seconds – claim by video!" } },
  golden_10: { de: { title: "🟢 Fünf Sterne von Accounts ohne Profilbild", desc: "10x TPS für 30 Sekunden – per Video sichern!" }, en: { title: "🟢 Five-Star Reviews From Accounts With No Avatar", desc: "10x TPS for 30 seconds – claim by video!" } },
  golden_11: { de: { title: "🟢 Kritiker verstummt, hält jetzt Aktienoptionen", desc: "10x TPS für 30 Sekunden – per Video sichern!" }, en: { title: "🟢 Critic Goes Quiet, Now Holds Stock Options", desc: "10x TPS for 30 seconds – claim by video!" } },
  golden_12: { de: { title: "🟢 Branchenpreis gewonnen, Jury besteht aus Sponsoren", desc: "10x TPS für 30 Sekunden – per Video sichern!" }, en: { title: "🟢 Industry Award Won, Jury Made Up of Sponsors", desc: "10x TPS for 30 seconds – claim by video!" } },
  golden_13: { de: { title: "🟢 Podcast nennt euch 'unterbewertet'. 40 Hörer.", desc: "10x TPS für 30 Sekunden – per Video sichern!" }, en: { title: "🟢 Podcast Calls You 'Undervalued'. 40 Listeners.", desc: "10x TPS for 30 seconds – claim by video!" } },
  golden_14: { de: { title: "🟢 Hochstufung auf 'Kaufen', vom eigenen Bankhaus", desc: "10x TPS für 30 Sekunden – per Video sichern!" }, en: { title: "🟢 Upgraded to 'Buy' by Your Own Underwriter", desc: "10x TPS for 30 seconds – claim by video!" } },
  golden_15: { de: { title: "🟢 Mitarbeiter postet stolz auf ProNet, sucht dort auch Jobs", desc: "10x TPS für 30 Sekunden – per Video sichern!" }, en: { title: "🟢 Employee Posts Proudly on ProNet, Job Hunting There Too", desc: "10x TPS for 30 seconds – claim by video!" } },

  bubble_1: { de: { title: "🔴 Behörde ermittelt – ihr hattet sie selbst angeschrieben", desc: "-35% VPS-Produktion & Burn Rate +1,5% für 30 Sekunden!" }, en: { title: "🔴 Regulator Investigates, You Emailed Them First", desc: "-35% VPS output & Burn Rate +1.5% for 30 seconds!" } },
  bubble_2: { de: { title: "🔴 Kritischer Artikel zur Burn Rate, Zahlen aus eurem Deck", desc: "-35% VPS-Produktion & Burn Rate +1,5% für 30 Sekunden!" }, en: { title: "🔴 Critical Burn Rate Article, Figures From Your Own Deck", desc: "-35% VPS output & Burn Rate +1.5% for 30 seconds!" } },
  bubble_3: { de: { title: "🔴 Großkunde kündigt – über euer eigenes Chatbot-Widget", desc: "-35% VPS-Produktion & Burn Rate +1,5% für 30 Sekunden!" }, en: { title: "🔴 Major Client Cancels – via Your Own Chatbot Widget", desc: "-35% VPS output & Burn Rate +1.5% for 30 seconds!" } },
  bubble_4: { de: { title: "🔴 Abstufung auf 'Verkaufen' – vom selben Analysten", desc: "-35% VPS-Produktion & Burn Rate +1,5% für 30 Sekunden!" }, en: { title: "🔴 Downgraded to 'Sell' by the Same Analyst as Before", desc: "-35% VPS output & Burn Rate +1.5% for 30 seconds!" } },
  bubble_5: { de: { title: "🔴 Sicherheitslücke gemeldet, Finder wartet seit acht Monaten", desc: "-35% VPS-Produktion & Burn Rate +1,5% für 30 Sekunden!" }, en: { title: "🔴 Vulnerability Reported, Finder Waited Eight Months", desc: "-35% VPS output & Burn Rate +1.5% for 30 seconds!" } },
  bubble_6: { de: { title: "🔴 Whistleblower-Thread, 12 Likes, alle von Anwälten", desc: "-35% VPS-Produktion & Burn Rate +1,5% für 30 Sekunden!" }, en: { title: "🔴 Whistleblower Thread, 12 Likes, All From Lawyers", desc: "-35% VPS output & Burn Rate +1.5% for 30 seconds!" } },
  bubble_7: { de: { title: "🔴 Konkurrenzprodukt ist besser, gebaut von euren Ex-Leuten", desc: "-35% VPS-Produktion & Burn Rate +1,5% für 30 Sekunden!" }, en: { title: "🔴 Competitor's Product Is Better, Built by Your Ex-Staff", desc: "-35% VPS output & Burn Rate +1.5% for 30 seconds!" } },
  bubble_8: { de: { title: "🔴 Runde geplatzt, Investor macht jetzt was mit Quanten", desc: "-35% VPS-Produktion & Burn Rate +1,5% für 30 Sekunden!" }, en: { title: "🔴 Round Collapses, Investor Is Into Quantum Now", desc: "-35% VPS output & Burn Rate +1.5% for 30 seconds!" } },
  bubble_9: { de: { title: "🔴 Stellungnahme gefordert – eure Antwort schrieb die KI", desc: "-35% VPS-Produktion & Burn Rate +1,5% für 30 Sekunden!" }, en: { title: "🔴 Statement Demanded, Your Reply Was AI-Generated", desc: "-35% VPS output & Burn Rate +1.5% for 30 seconds!" } },
  bubble_10: { de: { title: "🔴 Metriken im Deck geprüft, jemand hat nachgerechnet", desc: "-35% VPS-Produktion & Burn Rate +1,5% für 30 Sekunden!" }, en: { title: "🔴 Deck Metrics Reviewed, Someone Did the Math", desc: "-35% VPS output & Burn Rate +1.5% for 30 seconds!" } },
  bubble_11: { de: { title: "🔴 Greenwashing-Vorwurf, Bericht auf 400 GPUs gerendert", desc: "-35% VPS-Produktion & Burn Rate +1,5% für 30 Sekunden!" }, en: { title: "🔴 Greenwashing Claim, Report Rendered on 400 GPUs", desc: "-35% VPS output & Burn Rate +1.5% for 30 seconds!" } },
  bubble_12: { de: { title: "🔴 Ausfall in der Keynote, Demo lief zum Glück vom Band", desc: "-35% VPS-Produktion & Burn Rate +1,5% für 30 Sekunden!" }, en: { title: "🔴 Outage During Keynote, Demo Was Pre-Recorded Anyway", desc: "-35% VPS output & Burn Rate +1.5% for 30 seconds!" } },
  bubble_13: { de: { title: "🔴 Großkunde storniert, hat nie eine Rechnung bezahlt", desc: "-35% VPS-Produktion & Burn Rate +1,5% für 30 Sekunden!" }, en: { title: "🔴 Major Client Cancels, Never Paid an Invoice", desc: "-35% VPS output & Burn Rate +1.5% for 30 seconds!" } },
  bubble_14: { de: { title: "🔴 Skeptiker-Thread viral, meistgelesener Text über euch", desc: "-35% VPS-Produktion & Burn Rate +1,5% für 30 Sekunden!" }, en: { title: "🔴 Skeptic Thread Goes Viral, Most-Read Text About You", desc: "-35% VPS output & Burn Rate +1.5% for 30 seconds!" } },
  bubble_15: { de: { title: "🔴 Zweite Down-Round, intern 'Neubewertung' genannt", desc: "-35% VPS-Produktion & Burn Rate +1,5% für 30 Sekunden!" }, en: { title: "🔴 Second Down Round, Internally a 'Recalibration'", desc: "-35% VPS output & Burn Rate +1.5% for 30 seconds!" } },
};

export const GOLDEN_EVENT_IDS = Array.from({ length: 15 }, (_, i) => `golden_${i + 1}`);
export const BUBBLE_EVENT_IDS = Array.from({ length: 15 }, (_, i) => `bubble_${i + 1}`);
