// 30 Zufallsereignis-Texte (Konzept Abschnitt 10): 15 Golden Meme + 15 Bubble Pop
export const EVENTS_CONTENT = {
  golden_1: { de: { title: "🟢 Tech-Milliardär antwortet 'interessant' auf euren Post", desc: "10x TPS für 30 Sekunden – per Video sichern!" }, en: { title: "🟢 Tech Billionaire Replies 'Interesting' to Your Post", desc: "10x TPS for 30 seconds – claim by video!" } },
  golden_2: { de: { title: "🟢 Analyst nennt euch 'das nächste große Ding'. Schon wieder.", desc: "10x TPS für 30 Sekunden – per Video sichern!" }, en: { title: "🟢 Analyst Calls You 'The Next Big Thing'. Again.", desc: "10x TPS for 30 seconds – claim by video!" } },
  golden_3: { de: { title: "🟢 Accelerator gratuliert per Serienbrief", desc: "10x TPS für 30 Sekunden – per Video sichern!" }, en: { title: "🟢 Accelerator Sends Congratulations via Mail Merge", desc: "10x TPS for 30 seconds – claim by video!" } },
  golden_4: { de: { title: "🟢 '30 unter 30'-Nominierung, Gebühr bereits abgebucht", desc: "10x TPS für 30 Sekunden – per Video sichern!" }, en: { title: "🟢 '30 Under 30' Nomination, Fee Already Charged", desc: "10x TPS for 30 seconds – claim by video!" } },
  golden_5: { de: { title: "🟢 Wettbewerber kopiert euren Bug und nennt ihn Feature", desc: "10x TPS für 30 Sekunden – per Video sichern!" }, en: { title: "🟢 Competitor Copies Your Bug, Ships It as a Feature", desc: "10x TPS for 30 seconds – claim by video!" } },
  golden_6: { de: { title: "🟢 Investor teilt euren Launch, ohne ihn gelesen zu haben", desc: "10x TPS für 30 Sekunden – per Video sichern!" }, en: { title: "🟢 Investor Shares Your Launch Without Reading It", desc: "10x TPS for 30 seconds – claim by video!" } },
  golden_7: { de: { title: "🟢 Fachpresse übernimmt eure Pressemitteilung wörtlich", desc: "10x TPS für 30 Sekunden – per Video sichern!" }, en: { title: "🟢 Trade Press Reprints Your Press Release Verbatim", desc: "10x TPS for 30 seconds – claim by video!" } },
  golden_8: { de: { title: "🟢 Konkurrent ist insolvent, ihr erbt deren Beschwerden", desc: "10x TPS für 30 Sekunden – per Video sichern!" }, en: { title: "🟢 Competitor Folds, You Inherit Their Complaints", desc: "10x TPS for 30 seconds – claim by video!" } },
  golden_9: { de: { title: "🟢 Demo-Clip geht viral, aus den falschen Gründen", desc: "10x TPS für 30 Sekunden – per Video sichern!" }, en: { title: "🟢 Demo Clip Goes Viral for the Wrong Reasons", desc: "10x TPS for 30 seconds – claim by video!" } },
  golden_10: { de: { title: "🟢 Fünf Sterne von Accounts ohne Profilbild", desc: "10x TPS für 30 Sekunden – per Video sichern!" }, en: { title: "🟢 Five-Star Reviews From Accounts With No Avatar", desc: "10x TPS for 30 seconds – claim by video!" } },
  golden_11: { de: { title: "🟢 Kritiker verstummt, hält jetzt Aktienoptionen", desc: "10x TPS für 30 Sekunden – per Video sichern!" }, en: { title: "🟢 Critic Goes Quiet, Now Holds Stock Options", desc: "10x TPS for 30 seconds – claim by video!" } },
  golden_12: { de: { title: "🟢 Branchenpreis gewonnen, Jury besteht aus Sponsoren", desc: "10x TPS für 30 Sekunden – per Video sichern!" }, en: { title: "🟢 Industry Award Won, Jury Made Up of Sponsors", desc: "10x TPS for 30 seconds – claim by video!" } },
  golden_13: { de: { title: "🟢 Podcast nennt euch 'unterbewertet'. 40 Hörer.", desc: "10x TPS für 30 Sekunden – per Video sichern!" }, en: { title: "🟢 Podcast Calls You 'Undervalued'. 40 Listeners.", desc: "10x TPS for 30 seconds – claim by video!" } },
  golden_14: { de: { title: "🟢 Hochstufung auf 'Kaufen', vom eigenen Bankhaus", desc: "10x TPS für 30 Sekunden – per Video sichern!" }, en: { title: "🟢 Upgraded to 'Buy' by Your Own Underwriter", desc: "10x TPS for 30 seconds – claim by video!" } },
  golden_15: { de: { title: "🟢 Mitarbeiter postet stolz auf ProNet, sucht dort auch Jobs", desc: "10x TPS für 30 Sekunden – per Video sichern!" }, en: { title: "🟢 Employee Posts Proudly on ProNet, Job Hunting There Too", desc: "10x TPS for 30 seconds – claim by video!" } },

  bubble_1: { de: { title: "🔴 Untersuchung durch Aufsichtsbehörde eingeleitet", desc: "-35% VPS-Produktion & Burn Rate +1,5% für 30 Sekunden!" }, en: { title: "🔴 Regulator Opens an Investigation", desc: "-35% VPS output & Burn Rate +1.5% for 30 seconds!" } },
  bubble_2: { de: { title: "🔴 Kritischer Artikel über eure Burn Rate", desc: "-35% VPS-Produktion & Burn Rate +1,5% für 30 Sekunden!" }, en: { title: "🔴 Critical Article About Your Burn Rate", desc: "-35% VPS output & Burn Rate +1.5% for 30 seconds!" } },
  bubble_3: { de: { title: "🔴 Wichtiger Kunde kündigt öffentlich", desc: "-35% VPS-Produktion & Burn Rate +1,5% für 30 Sekunden!" }, en: { title: "🔴 A Major Customer Cancels Publicly", desc: "-35% VPS output & Burn Rate +1.5% for 30 seconds!" } },
  bubble_4: { de: { title: "🔴 Analyst stuft auf 'Sell' herab", desc: "-35% VPS-Produktion & Burn Rate +1,5% für 30 Sekunden!" }, en: { title: "🔴 Analyst Downgrades to 'Sell'", desc: "-35% VPS output & Burn Rate +1.5% for 30 seconds!" } },
  bubble_5: { de: { title: "🔴 Sicherheitslücke wird bekannt", desc: "-35% VPS-Produktion & Burn Rate +1,5% für 30 Sekunden!" }, en: { title: "🔴 A Security Vulnerability Comes to Light", desc: "-35% VPS output & Burn Rate +1.5% for 30 seconds!" } },
  bubble_6: { de: { title: "🔴 Ehemaliger Mitarbeiter postet Whistleblower-Thread", desc: "-35% VPS-Produktion & Burn Rate +1,5% für 30 Sekunden!" }, en: { title: "🔴 Former Employee Posts a Whistleblower Thread", desc: "-35% VPS output & Burn Rate +1.5% for 30 seconds!" } },
  bubble_7: { de: { title: "🔴 Konkurrent launcht besseres, billigeres Produkt", desc: "-35% VPS-Produktion & Burn Rate +1,5% für 30 Sekunden!" }, en: { title: "🔴 A Competitor Launches a Better, Cheaper Product", desc: "-35% VPS output & Burn Rate +1.5% for 30 seconds!" } },
  bubble_8: { de: { title: "🔴 Investorenrunde platzt in letzter Minute", desc: "-35% VPS-Produktion & Burn Rate +1,5% für 30 Sekunden!" }, en: { title: "🔴 Funding Round Collapses at the Last Minute", desc: "-35% VPS output & Burn Rate +1.5% for 30 seconds!" } },
  bubble_9: { de: { title: "🔴 Regulierungsbehörde fordert Stellungnahme", desc: "-35% VPS-Produktion & Burn Rate +1,5% für 30 Sekunden!" }, en: { title: "🔴 Regulator Demands a Statement", desc: "-35% VPS output & Burn Rate +1.5% for 30 seconds!" } },
  bubble_10: { de: { title: "🔴 Fragwürdige Metriken im Pitch Deck aufgedeckt", desc: "-35% VPS-Produktion & Burn Rate +1,5% für 30 Sekunden!" }, en: { title: "🔴 Questionable Metrics in the Pitch Deck Exposed", desc: "-35% VPS output & Burn Rate +1.5% for 30 seconds!" } },
  bubble_11: { de: { title: "🔴 Community wirft euch Greenwashing vor", desc: "-35% VPS-Produktion & Burn Rate +1,5% für 30 Sekunden!" }, en: { title: "🔴 Community Accuses You of Greenwashing", desc: "-35% VPS output & Burn Rate +1.5% for 30 seconds!" } },
  bubble_12: { de: { title: "🔴 Server-Ausfall während der Keynote", desc: "-35% VPS-Produktion & Burn Rate +1,5% für 30 Sekunden!" }, en: { title: "🔴 Server Outage During the Keynote", desc: "-35% VPS output & Burn Rate +1.5% for 30 seconds!" } },
  bubble_13: { de: { title: "🔴 Großer Kunde storniert Vertrag", desc: "-35% VPS-Produktion & Burn Rate +1,5% für 30 Sekunden!" }, en: { title: "🔴 A Major Client Cancels Their Contract", desc: "-35% VPS output & Burn Rate +1.5% for 30 seconds!" } },
  bubble_14: { de: { title: "🔴 Skeptischer Thread wird viral", desc: "-35% VPS-Produktion & Burn Rate +1,5% für 30 Sekunden!" }, en: { title: "🔴 A Skeptical Thread Goes Viral", desc: "-35% VPS output & Burn Rate +1.5% for 30 seconds!" } },
  bubble_15: { de: { title: "🔴 Zweite Down-Round in einem Jahr", desc: "-35% VPS-Produktion & Burn Rate +1,5% für 30 Sekunden!" }, en: { title: "🔴 Second Down Round in One Year", desc: "-35% VPS output & Burn Rate +1.5% for 30 seconds!" } },
};

export const GOLDEN_EVENT_IDS = Array.from({ length: 15 }, (_, i) => `golden_${i + 1}`);
export const BUBBLE_EVENT_IDS = Array.from({ length: 15 }, (_, i) => `bubble_${i + 1}`);
