import {
  Activity, AlertTriangle, Atom, Award, BarChart2, Bomb, BookOpen, Briefcase,
  Building2, Calculator, CalendarCheck, CheckCircle2, Clock, Clover, Code, Compass,
  Copy, Cpu, Crosshair, Crown, Database, DollarSign, FileCheck, FileSpreadsheet,
  FileText, Flag, Flame, Frown, Globe, Grid, HeartHandshake, Keyboard,
  Landmark, Layers, Leaf, Loader2, Lock, Megaphone, MessageSquare, Mouse,
  Network, Newspaper, Package, Paperclip, PlusCircle, Presentation, Recycle, RefreshCw,
  Repeat, Rocket, RotateCw, Scale, Scan, Scissors, Search, SearchCheck,
  Server, Shield, ShieldAlert, ShieldCheck, Siren, Smile, Sparkles, Star,
  Sun, Target, Terminal, Thermometer, ThermometerSnowflake, Trash2, Trees, TrendingDown,
  TrendingUp, Trophy, Truck, Tv, User, UserCheck, UserCog, UserMinus,
  UserX, Users, Video, Wand2, X, Zap,
} from 'lucide-react';

// Namentliche Einzel-Imports statt `import * as Icons from 'lucide-react'`: Mehrere
// Stellen im Code lösen Icon-Komponenten dynamisch über einen zur Laufzeit bekannten
// String auf (Datenfelder wie buildingsData.js `icon: 'Cpu'`, Achievements, Buzzwords,
// ...). Ein Namespace-Import + `Icons[name]`-Zugriff macht das für den Bundler
// statisch nicht mehr analysierbar - Rollup kann dann nicht beweisen, dass irgendein
// Icon UNBENUTZT ist, und packt sicherheitshalber alle ~4050 lucide-Icons ins Bundle
// (verifiziert: selbst Croissant oder FerrisWheel tauchten im Build auf, obwohl im
// gesamten Code nirgends referenziert). Diese Datei importiert nur die 86
// tatsächlich verwendeten Namen einzeln - jetzt kann Rollup den Rest wegschütteln.
//
// Bei einem neuen Icon in einer Datendatei: hier ergänzen (Import-Zeile + ICON_MAP-
// Eintrag), sonst rendert getIcon() den fallback und das neue Icon fehlt lautlos.
const ICON_MAP = {
  Activity,
  AlertTriangle,
  Atom,
  Award,
  BarChart2,
  Bomb,
  BookOpen,
  Briefcase,
  Building2,
  Calculator,
  CalendarCheck,
  CheckCircle2,
  Clock,
  Clover,
  Code,
  Compass,
  Copy,
  Cpu,
  Crosshair,
  Crown,
  Database,
  DollarSign,
  FileCheck,
  FileSpreadsheet,
  FileText,
  Flag,
  Flame,
  Frown,
  Globe,
  Grid,
  HeartHandshake,
  Keyboard,
  Landmark,
  Layers,
  Leaf,
  Loader2,
  Lock,
  Megaphone,
  MessageSquare,
  Mouse,
  Network,
  Newspaper,
  Package,
  Paperclip,
  PlusCircle,
  Presentation,
  Recycle,
  RefreshCw,
  Repeat,
  Rocket,
  RotateCw,
  Scale,
  Scan,
  Scissors,
  Search,
  SearchCheck,
  Server,
  Shield,
  ShieldAlert,
  ShieldCheck,
  Siren,
  Smile,
  Sparkles,
  Star,
  Sun,
  Target,
  Terminal,
  Thermometer,
  ThermometerSnowflake,
  Trash2,
  Trees,
  TrendingDown,
  TrendingUp,
  Trophy,
  Truck,
  Tv,
  User,
  UserCheck,
  UserCog,
  UserMinus,
  UserX,
  Users,
  Video,
  Wand2,
  X,
  Zap,
};

export function getIcon(name, fallback = 'Zap') {
  return ICON_MAP[name] || ICON_MAP[fallback] || Zap;
}
